### PR TITLE
Upgrade dependencies; support psc-0.7.4

### LINKED ISSUE #18: bring dependencies up to date
PR incoming.

### LINKED ISSUE #19: psc-0.7.4 compatibility
This package currently introduces orphan instances

### PR DESCRIPTION
**Pull request by jonsterling**
- requires PureScript `^0.7.4` [resolves #19]
- upgraded `purescript-strings`, `purescript-parsing` and `purescript-strongcheck` (and transitive dependencies thereof, including `purescript-transformers`) [resolves #18]
- fixed orphan instances [#19]
- fix various aspects of the build; use `gulp-mocha` rather than relying on ambient "mocha" executable
- added explicit export lists
- standardized whitespace, removed trailing whitespace
- added myself to the authors list

Note: we can't yet upgrade SlamData to this version because of our reliance on an old compiler, but I'd like to get it up to date, so that things go smoothly when we do the big upgrade.

### CODE REVIEW

**Comment by cryogenian** [comment]
Awesome! Could you please replace `Data.Semiring.Disjunctive` with `Data.Monoid.Disj`?

**Comment by jonsterling** [comment]
@cryogenian Great idea, sure!

**Comment by jonsterling** [comment]
@cryogenian OK, sorry for the delay; `Disjunctive` is now removed, and replaced with new version of `Data.Monoid.Disj` that supports `Semiring`.

**Comment by cryogenian** [comment]
Thanks!

**Pull request merged**
